import os
import json
import subprocess
import glob
from typing import Any, Dict, List
import cv2
import time
from detectors.yolo_detector import YOLODetector
from detectors.byte_track_tracker import ByteTrackTracker
from detectors.deep_sort_tracker import DeepSortDetector
from database.database import Database


class VideoProcessor:
    def __init__(self, video_path: str, output_dir: str, database_path: str, interval: int = 30, tracker_arg: str = 'bytetrack'):
        self.video_path = video_path
        self.output_dir = output_dir
        self.frames_output_dir = os.path.join(self.output_dir, "extracted_frames")
        os.makedirs(self.frames_output_dir, exist_ok=True)
        self.database_path = database_path
        self.db = Database(self.database_path)
        self.detector = YOLODetector()
        self.tracker = ByteTrackTracker(self.output_dir)
        self.deepsort_tracker = DeepSortDetector(self.output_dir)
        self.log_entries = {}
        self.initial_yolo_results_log = {}
        self.video_info = self.get_video_info()
        self.interval = interval
        self.tracker_arg = tracker_arg

    def get_video_info(self) -> Dict[str, Any]:
        """ Function to extract video information using FFmpeg. """

        # ffprobe command to extract video information in JSON format
        ffprobe_command = [
            'ffprobe', '-v', 'error', '-select_streams', 'v:0', '-show_entries',
            'stream=width,height,avg_frame_rate,nb_frames,duration', '-of', 'json', self.video_path
        ]
        
        # Executes the ffprobe command
        result = subprocess.run(ffprobe_command, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        
        # Parse the result as JSON
        video_info = json.loads(result.stdout)
        
        # Extracts required information
        if 'streams' in video_info and len(video_info['streams']) > 0:
            stream_info = video_info['streams'][0]
            width = stream_info.get('width', 'Unknown')
            height = stream_info.get('height', 'Unknown')
            duration = stream_info.get('duration', 'Unknown')
            nb_frames = stream_info.get('nb_frames', 'Unknown')
            avg_frame_rate = stream_info.get('avg_frame_rate', 'Unknown')
            
            # Parses frame rate (if it's available as a fraction)
            fps = eval(avg_frame_rate) if '/' in avg_frame_rate else avg_frame_rate
            
            return {
                'width': width,
                'height': height,
                'duration': float(duration),
                'nb_frames': int(nb_frames),
                'fps': fps
            }
        
        return None
    

    def calculate_expected_frames(self) -> int:
        """Calculate the expected number of frames to be extracted."""

        total_frames = self.video_info['nb_frames']
        return total_frames // self.interval
    

    def frames_already_extracted(self) -> bool:
        """Check if the required number of frames has already been extracted."""

        # Count the number of frame files in the output directory
        existing_frames_count = len([
            f for f in os.listdir(self.frames_output_dir) 
            if f.startswith("frame_") and f.endswith(".jpg")
        ])
        
        # Calculate the expected number of frames
        expected_frames_count = self.calculate_expected_frames()
        
        # Return True if the expected frames are already extracted, False otherwise
        return existing_frames_count + 3 >= expected_frames_count and existing_frames_count - 3 <= expected_frames_count

    def extract_frames(self):
        """ Function to extract frames from a video using FFmpeg. """
        print(self.video_info)

        # Check if frames already extracted
        if self.frames_already_extracted():
            print("Frames are already extracted. Skipping extraction.")
            return

        ffmpeg_command = [
            'ffmpeg', '-fflags', '+genpts', '-i', self.video_path,
            '-vf', f"scale=640:-2, select='not(mod(n\\,{self.interval}))', format=yuvj420p",
            '-fps_mode', 'vfr',
            # Set higher quality for better object detection
            '-q:v', '2',
            # Sets pixel format to yuvj420p for better accuracy in object detection
            '-pix_fmt', 'yuvj420p',
            '-to', str(self.video_info['duration']),
            '-start_number', '0',
            # Output frame path
            f'{self.frames_output_dir}/frame_%04d.jpg'
        ]

        print("Extracting frames with FFmpeg...")
        subprocess.run(ffmpeg_command, check=True)
        print("Frame extraction complete.")

    def process_video(self):
        """ Function to process video frames for object detection and tracking. """

        # Run FFmpeg extraction before processing frames
        self.extract_frames()

        start_time = time.time()
        # Load frames generated by FFmpeg
        frame_files = sorted(glob.glob(os.path.join(self.frames_output_dir, 'frame_*.jpg')))
        
        for frame_number, frame_file in enumerate(frame_files):
            print(f"Processing frame {frame_file}")
            # Adjust timestamp for every nth frame
            timestamp = frame_number * (self.interval / self.video_info['fps'])
            # Insert frame into the database
            self.db.insert_frame(frame_number, timestamp)

            frame = cv2.imread(frame_file)
            
            # Initial YOLO detections + their log
            results, detections = self.detector.detect_objects(frame, timestamp)
            self.initial_yolo_results_log[frame_number] = [vars(det) for det in detections]
            self.add_detections_in_db(detections, frame_number)

            # Refine detection with tracking, choose the tracker based on the argument if not selected skip tracking (initial index)
            if self.tracker_arg != '-':
                if(self.tracker_arg == 'bytetrack'):
                    tracked_detections = self.tracker.update_tracks(results, frame, frame_number)
                    self.log_entries[frame_number] = tracked_detections
                elif(self.tracker_arg == 'deepsort'):
                    tracked_detections = self.deepsort_tracker.track(detections, frame, frame_number=frame_number)
                    self.log_entries[frame_number] = [vars(det) for det in tracked_detections]

        self.save_log(self.initial_yolo_results_log, name='initial_yolo_results_log')
        self.save_log(self.log_entries)
        print(f"Processing complete. Total time taken: {time.time() - start_time:.2f} seconds.")

    def add_detections_in_db(self, detections, frame_number: int):
        """Accumulate detections and insert in bulk into the database."""
        # List to hold all detections for the current frame
        bulk_detections = []

        for detection in detections:
            detection_data = {
                'frame_number': frame_number,
                'track_id': detection.get('track_id', None),
                'direction': detection.get('direction', None),
                'class_name': detection.get('class_name', None),
                'class_id': detection.get('class_id', None),
                'bbox': detection.get('bbox', None),
                'confidence': detection.get('confidence', None),
                'timestamp': detection.get('timestamp', None),
                'dominant_color': detection.get('dominant_color', None),
            }
            # Append to the bulk list
            bulk_detections.append(detection_data)

        # Insert all detections for this frame in bulk
        self.db.bulk_insert_detections(bulk_detections)

    def save_log(self, log, name: str = 'detection_log'):
        log_file_path = os.path.join(self.output_dir, f"{name}.json")
        with open(log_file_path, 'w') as log_file:
            json.dump(log, log_file, indent=4)
        print(f"Log saved to '{log_file_path}'.")